### ISSUE TITLE
Multiple DnD widgets on the same page

### ISSUE THREAD

**Issue by Arthurgoujon** [Itvisors/mendix-ReactDnD#3]
Many thanks for a great widget! I have been using the widget successfully to let user re-sequence a list of jobs for a day.

Now I am building a more complex use case where users need to re-sequence jobs lists for several days on the same page.
I have a list-view for the days, and for each day, I want to show the list of jobs in a DnD widget, so they can be sequenced. 

When the user drags any item, the DnD widgets for all other days immediately crashes: "could not render widget". 
Do you know of any limitations when rendering a list of multiple DnD widgets on the page? 

Thank you

**Comment by mgroeneweg** [comment]
Hi,

Having multiple DnD widgets on the same page is not supported. You can configure multiple datasource containers to list each day separately, or use a single datasource to list all jobs.

With regards,

Marcel

**Comment by Arthurgoujon** [comment]
Thank you Marcel, I would like to rephrase to make sure I understood correctly: 
- using the DnD widget in a list view is not supported
- using the DnD widget several times in the same page is ok as long as it is in separate data source. For instance in a dataview for day 1, another data view for day 2 etc. 
- alternatively I could display all jobs from all days in a single DnD

Let me know if I misunderstood anything. 
thank you!

**Comment by mgroeneweg** [comment]
Only one DnD widget per page, use a container in the widget itself to create lists of items.

**Comment by Arthurgoujon** [comment]
Understood, I will try this. Thank you
